### ISSUE TITLE
Missing appimage for continuous release

### ISSUE THREAD

**Issue by blutack** [collin80/SavvyCAN#208]
I could be missing something but I can't find the appimage for the continuous release. It would be great to add it back if possible?

**Comment by collin80** [comment]
Looks like you're right. It got saved as a draft because I've been messing around with getting all three platforms (Windows, OSX, LINUX) to compile automatically with TravisCI. The other two are supposed to still be "Drafts" so only I can see them but it saved all three that way. I published the files for now so you can grab the AppImage.

**Comment by blutack** [comment]
That's great, thanks very much for the quick response!
