### ISSUE TITLE
Trigger timing is not correct in Windows 

### ISSUE THREAD

**Issue by zeng1984** [collin80/SavvyCAN#213]
Hello SavvyCAN author,
      you did great jobs in this tools. 
![image](https://user-images.githubusercontent.com/28468779/65404395-dec4f600-de0a-11e9-8534-29d77abdc1e2.png)

background:
after comment qcustomplot.cpp line 909 and line 910, compiled base on windows platform, Qt debug mode, on Frame Sender window, I connected Vector CANcasexl, and one PCB which was sending some CAN Messages on CAN bus, I tried to use simulation function like Frame Sender, 
En      Bus     ID  Len  Ext   Rem  Data                 Trigger Modidfcations  Count
Yes    can     0x178 3  No  No    0x01,0x03,0x4    400      No              
in Trigger lineEdit I write 400 or other value, but the cyclic timing is around 100ms.
               is it a Software bug?  

Thanks &regards,
Xiangwei

**Comment by collin80** [comment]
Sorry for not getting to this sooner. The problem is that the trigger isn't just timing but could trigger based on received frames and such too. The proper trigger in your case is 400ms not 400. It is specifically looking for the ms part to create the timing. You should be able to push F1 for help and it will tell you about the various things you can put in the trigger field.
