### ISSUE TITLE
it seems to memory leak if the CAN signals were sent. 

### ISSUE THREAD

**Issue by zeng1984** [collin80/SavvyCAN#214]
Hello SavvyCAN author,
      you did great jobs in this tools. 

background:
after comment qcustomplot.cpp line 909 and line 910, compiled base on windows platform, Qt debug mode, on Frame Sender window, I connected Vector CANcasexl, and one PCB which was sending some CAN Messages on CAN bus. And this PCB was sending CAN messages continuously. 
              Then to check this thread in windows task manger. And found memory leak.
you can see the screenshot and check Qtcreator.exe*32 ,the memrory is increasing. 
![image](https://user-images.githubusercontent.com/28468779/65404948-58f67a00-de0d-11e9-8742-0f8147e52b39.png)
 
![image](https://user-images.githubusercontent.com/28468779/65404960-627fe200-de0d-11e9-9cc2-75431cf8fab7.png)
![image](https://user-images.githubusercontent.com/28468779/65404995-7deaed00-de0d-11e9-9e87-b54b567bc84a.png)
              
             can you please check it and let me know if it's a memory leak ? 

Thanks &regards,
Xiangwei

**Comment by collin80** [comment]
I don't know that it is a memory leak. If you do have CAN frames coming in then they are being buffered in RAM so that you can do processing on them, save them, etc. QT will allocate buffers in chunks so it would be normal to see the RAM usage jump up in increments. The program reserves a big chunk of RAM in the very beginning so that large captures can happen into a contiguous buffer without needing to move it all to a bigger place in RAM. Initially this RAM is somewhat "shadow" allocated in that it is not truly reported as in use yet. But the program asks to reserve a lot of RAM for itself in the very beginning. As you load or capture frames it allocates within that block. This buffer is not generally shrunk when you clear the frames either. It clears them but leaves the buffer as big as it was and you can continue to fill it up again. But, I don't see any actual leak. If you load a file that is the same size or smaller compared to the last batch of data you had loaded you'll find that RAM usage really doesn't increase.
