### ISSUE TITLE
Error in dbc/dbchandler when make

### ISSUE THREAD

**Issue by tsunemitsu711** [collin80/SavvyCAN#267]
In dbc/dhchandler.cpp, line 1755, error: 'class QList<DBCFile>' has no member named 'swapItemsAt '　
I get an error like this and it fails. Is there any solution to this problem?

**Comment by collin80** [comment]
The solution is to either upgrade your version of QT or change that function call to swapAt instead. For some reason I may never understand, QT deprecated the old name so I changed the name in order to squash a warning about using the old name. But, the new name doesn't exist until a very recent version of QT.

**Comment by tsunemitsu711** [comment]
Thank you for your reply.
Thanks to you, I was able to move it successfully.
It didn't work with 'swapAt', but it worked when I changed it to 'swap'.
