### ISSUE TITLE
Darker Yellow for Detailed Frame Info Byte 5?

### ISSUE THREAD

**Issue by FrankM54** [collin80/SavvyCAN#581]
First of all, thanks to all who continue to make this such a fantastic program!!

I use the "Detailed Frame Analysis" very often and was wondering how can I change the yellow graph colour for byte 5 to something a little darker. (maybe orange?)

<img width="304" alt="image" src="https://user-images.githubusercontent.com/77734337/219371667-2f2790ec-9144-4c43-8871-fda00ad7a212.png">

As you can see, it is difficult to see the graph line.

With the previous version, I would click on byte 5 to turn the graphed line blue, so I can see it.
However, since everything is now separate (which is really nice!) I can't select a graph line to make it darker.

Screen shot from V211 Feb 15 2023, on Mac OS 12.6.3

Thanks in advance!

**Comment by FrankM54** [comment]
Found it:
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/77734337/219392573-6de8a41e-e9bc-49ea-b1bb-5fdab5cc5127.png">

Here are the QT default colours:
<img width="670" alt="image" src="https://user-images.githubusercontent.com/77734337/219393162-2bddd37a-76c8-4cf7-b5a5-94919af6d9a5.png">

I can change it to dark orange, but don't know how to compile for Mac.
Are there any instructions on how to do this?
I would really like to learn and do have iOS app experience, so not a total newbie.

**Comment by collin80** [comment]
I just pushed a change to make it use QT:darkYellow instead of QT::yellow. This should make it easier to see. It's more of a brown color now if you ask me but it's certainly more visible.

Unfortunately, compiling QT apps can be a little bit of a pain as you need to get the QT framework installed. The official way to do that is to go to qt.io and download the open source installer for QT. This then makes you sign up for an account (its free) in order to download anything. Thereafter you can use it to download the newest version of QT 5.15 that you can find. I think it might be 5.15.2. QT uses QSerialBus so you may need to download that as an add-on. I don't remember if it is an optional add-on or not. Once you have that you obviously need XCode as well but if you do iOS development then I assume you've already got that installed. Then, the easiest approach to compiling is to have QTCreator installed and open that. You would open the .pro file within the SavvyCAN directory and tell it to use your installed QT 5.15 files. From there you can do a debug or release build and it should have all the pieces necessary to do so.

Alternatively, you might have an easier time doing it straight from the command line by following the same steps that the CI build does. It looks like brew can install QT for you:

https://github.com/collin80/SavvyCAN/blob/master/.github/workflows/build.yml#L41

Or, the CI build is now complete so you can download a binary if you can't get things working.
