### ISSUE TITLE
cannot select port when using socketcan

### ISSUE THREAD

**Issue by alan707** [collin80/SavvyCAN#66]
I was able to compile SavvyCAN on ubuntu and it works great.  The only issue I found so far is that when choosing socketcan to connect through a socketcan-compatible device, the dropdown menu is empty and therefore I cannot select a port (e.g. /dev/ttyACM0).  Any suggestions?

**Comment by collin80** [comment]
Which version of SavvyCAN did you compile? The master branch? If that's the case then unfortunately socketcan support isn't complete and there's only the suggestion of hope that it could work. The WIP2 branch has a working version of socketcan support. In that version you can select socketcan and you'll get a textbox instead of a combo box. In the textbox you can type in the name of your socketcan device. I didn't write the socketcan support but I think you want to enter in the name of the device minus the /dev/ part so if your board is /dev/scan0 then enter scan0 as the name.
